### ISSUE TITLE
Editor can't create script, when It has a private ctor

### ISSUE THREAD

**Issue by TheJustLink** [FlaxEngine/FlaxEngine#1018]
**Issue description:**
Found few issues, when I try to use constructors in script.

It seems here the problem is that It cannot find a private ctor through activator (a private flag is not installed?). It can be useful if you want to create scripts in other code. Now you have to make a public ctor, but this breaks the contract, you can create objects without the required parameters. It would be cool to be able to leave a private ctor or even get rid of it (create scripts without a ctor, it seems even faster).

Instead of activator, you can use:
```cs
RuntimeHelpers.GetUninitializedObject(Type)
// Or
FormatterServices.GetUninitializedObject(Type)
```

Output log:
```
[ 02:22:42.448 ]: [Warning] Exception has been thrown during Window.OnMouseUp. Default constructor not found for type Game.CrashMe
Stack strace:
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) <0x16903654e80 + 0x0048a> in <ccba8f4931be433d979e22082f9d6862>:0 
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) <0x16903654d00 + 0x000fa> in <ccba8f4931be433d979e22082f9d6862>:0 
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) <0x169036549e0 + 0x00192> in <ccba8f4931be433d979e22082f9d6862>:0 
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) <0x169036546b0 + 0x00282> in <ccba8f4931be433d979e22082f9d6862>:0 
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) <0x169036545c0 + 0x00082> in <ccba8f4931be433d979e22082f9d6862>:0 
  at System.Activator.CreateInstance (System.Type type) <0x169036544d0 + 0x00072> in <ccba8f4931be433d979e22082f9d6862>:0 
  at FlaxEditor.Scripting.ScriptType.CreateInstance () [0x0000e] in F:\FlaxEngine\Source\Editor\Scripting\ScriptType.cs:894 
  at FlaxEditor.Actions.AddRemoveScript.DoAdd () [0x00044] in F:\FlaxEngine\Source\Editor\Undo\Actions\AddRemoveScriptAction.cs:164 
  at FlaxEditor.Actions.AddRemoveScript.Do () [0x00008] in F:\FlaxEngine\Source\Editor\Undo\Actions\AddRemoveScriptAction.cs:114 
  at FlaxEditor.MultiUndoAction.Do () [0x00004] in F:\FlaxEngine\Source\Editor\Undo\MultiUndoAction.cs:57 
  at FlaxEditor.CustomEditors.Dedicated.DragAreaControl.AddScripts (System.Collections.Generic.List`1[T] items) [0x00083] in F:\FlaxEngine\Source\Editor\CustomEditors\Dedicated\ScriptsEditor.cs:243 
  at FlaxEditor.CustomEditors.Dedicated.DragAreaControl.AddScript (FlaxEditor.Scripting.ScriptType item) [0x0000e] in F:\FlaxEngine\Source\Editor\CustomEditors\Dedicated\ScriptsEditor.cs:179 
  at FlaxEditor.CustomEditors.Dedicated.DragAreaControl.<OnAddScriptButtonClicked>b__5_0 (FlaxEditor.GUI.ItemsListContextMenu+Item item) [0x00000] in F:\FlaxEngine\Source\Editor\CustomEditors\Dedicated\ScriptsEditor.cs:73 
  at FlaxEditor.GUI.ItemsListContextMenu.OnClickItem (FlaxEditor.GUI.ItemsListContextMenu+Item item) [0x00006] in F:\FlaxEngine\Source\Editor\GUI\ItemsListContextMenu.cs:323 
  at FlaxEditor.GUI.ItemsListContextMenu+Item.OnMouseUp (FlaxEngine.Float2 location, FlaxEngine.MouseButton button) [0x00013] in F:\FlaxEngine\Source\Editor\GUI\ItemsListContextMenu.cs:159 
  at FlaxEngine.GUI.ContainerControl.OnMouseUp (FlaxEngine.Float2 location, FlaxEngine.MouseButton button) [0x00039] in F:\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:980 
  at FlaxEngine.GUI.ContainerControl.OnMouseUp (FlaxEngine.Float2 location, FlaxEngine.MouseButton button) [0x00039] in F:\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:980 
  at FlaxEngine.GUI.ContainerControl.OnMouseUp (FlaxEngine.Float2 location, FlaxEngine.MouseButton button) [0x00039] in F:\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:980 
  at FlaxEditor.GUI.ContextMenu.ContextMenuBase.OnMouseUp (FlaxEngine.Float2 location, FlaxEngine.MouseButton button) [0x00000] in F:\FlaxEngine\Source\Editor\GUI\ContextMenu\ContextMenuBase.cs:500 
  at FlaxEngine.GUI.ContainerControl.OnMouseUp (FlaxEngine.Float2 location, FlaxEngine.MouseButton button) [0x00039] in F:\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:980 
  at FlaxEngine.GUI.WindowRootControl.OnMouseUp (FlaxEngine.Float2 location, FlaxEngine.MouseButton button) [0x00021] in F:\FlaxEngine\Source\Engine\UI\GUI\WindowRootControl.cs:305 
  at FlaxEngine.Window.Internal_OnMouseUp (FlaxEngine.Float2& mousePos, FlaxEngine.MouseButton button) [0x0002e] in F:\FlaxEngine\Source\Engine\Platform\Window.cs:242 
[ 02:22:42.448 ]: [Error] Exception has been thrown during Window.OnMouseUp.
Default constructor not found for type Game.CrashMe
```

**Steps to reproduce:**
1. Create script:
```cs
class CrashMe : Script
{
        private CrashMe() { }
        public CrashMe(object argument) { }
}
```
2. Attach to any object.
3. Remove script from object
4. Attach script again and get the error in output log.

**Flax version:** [1.5.6339](https://github.com/FlaxEngine/FlaxEngine/releases/tag/1.5.6339)

**Comment by TheJustLink** [comment]
@mafiesto4, Thank you for crash fix! #1019

I checked, everything works. But within this problem, I realized that the constructor must be called, because the fields can have initial values that will then move to the constructor.

But I would like to be able to forbid to call the constructor without parameters. Now Editor for some reason only looks for public constructor, when you attach script to actor, private constructor doesn't work 🤔

I get this error when I use private constructor and try to attach script:
```cfg
[ 00:46:09.129 ]: [Warning] Exception has been thrown during Window.OnMouseUp. No parameterless constructor defined for type 'Game.CrashMe'.
Stack strace:
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at FlaxEditor.Scripting.ScriptType.CreateInstance() in C:\Program Files (x86)\Flax\FlaxEngine\Source\Editor\Scripting\ScriptType.cs:line 895
   at FlaxEditor.Actions.AddRemoveScript.DoAdd() in C:\Program Files (x86)\Flax\FlaxEngine\Source\Editor\Undo\Actions\AddRemoveScriptAction.cs:line 165
   at FlaxEditor.Actions.AddRemoveScript.Do() in C:\Program Files (x86)\Flax\FlaxEngine\Source\Editor\Undo\Actions\AddRemoveScriptAction.cs:line 115
   at FlaxEditor.MultiUndoAction.Do() in C:\Program Files (x86)\Flax\FlaxEngine\Source\Editor\Undo\MultiUndoAction.cs:line 57
   at FlaxEditor.CustomEditors.Dedicated.DragAreaControl.AddScripts(List`1 items) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Editor\CustomEditors\Dedicated\ScriptsEditor.cs:line 244
   at FlaxEditor.CustomEditors.Dedicated.DragAreaControl.AddScript(ScriptType item) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Editor\CustomEditors\Dedicated\ScriptsEditor.cs:line 180
   at FlaxEditor.CustomEditors.Dedicated.DragAreaControl.<OnAddScriptButtonClicked>b__5_0(Item item) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Editor\CustomEditors\Dedicated\ScriptsEditor.cs:line 74
   at FlaxEditor.GUI.ItemsListContextMenu.OnClickItem(Item item) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Editor\GUI\ItemsListContextMenu.cs:line 323
   at FlaxEditor.GUI.ItemsListContextMenu.Item.OnMouseUp(Float2 location, MouseButton button) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Editor\GUI\ItemsListContextMenu.cs:line 159
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEditor.GUI.ContextMenu.ContextMenuBase.OnMouseUp(Float2 location, MouseButton button) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Editor\GUI\ContextMenu\ContextMenuBase.cs:line 500
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEngine.GUI.WindowRootControl.OnMouseUp(Float2 location, MouseButton button) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Engine\UI\GUI\WindowRootControl.cs:line 305
   at FlaxEngine.Window.Internal_OnMouseUp(Float2& mousePos, MouseButton button) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Engine\Platform\Window.cs:line 242
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet2`3.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 309
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in C:\Program Files (x86)\Flax\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 675
[ 00:46:09.129 ]: [Error] Exception has been thrown during Window.OnMouseUp.
No parameterless constructor defined for type 'Game.CrashMe'.
```

**Comment by mafiesto4** [comment]
Good catch. Yeah, this should match the creation of the object in Dotnet runtime so private ctor will work fine in 92b155dbb316cbc0409f1261997f9d021faadce9
