### ISSUE TITLE
Problem with Splines

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1219]
You cannot delete splines from scene.

**Flax version:**
1.6

**Comment by Tryibion** [comment]
Here is the error in the output log
```
[ 00:00:05.974 ]: [Warning] Exception has been thrown during Window.OnKeyDown. The specified Type must not be a generic type. (Parameter 't')
Stack strace:
   at System.Runtime.InteropServices.Marshal.SizeOf(Type t)
   at FlaxEngine.Spline.get_SplineKeyframes() in Z:\Flax\Source\FlaxEngine\Source\Engine\Level\Spline.cs:line 26
   at FlaxEngine.Spline.GetSplineKeyframe(Int32 index) in Z:\Flax\Source\FlaxEngine\Source\Engine\Level\Spline.cs:line 48
   at FlaxEditor.SceneGraph.Actors.SplineNode.SplinePointNode.get_State() in Z:\Flax\Source\FlaxEngine\Source\Editor\SceneGraph\Actors\SplineNode.cs:line 71
   at FlaxEditor.Actions.DeleteActorsAction..ctor(List`1 nodes, Boolean isInverted) in Z:\Flax\Source\FlaxEngine\Source\Editor\Undo\Actions\DeleteActorsAction.cs:line 73
   at FlaxEditor.Modules.SceneEditingModule.Delete() in Z:\Flax\Source\FlaxEngine\Source\Editor\Modules\SceneEditingModule.cs:line 439
   at FlaxEditor.Options.InputActionsContainer.Process(Editor editor, Control control, KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Editor\Options\InputBinding.cs:line 477
   at FlaxEditor.GUI.Docking.DockWindow.OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Editor\GUI\Docking\DockWindow.cs:line 480
   at FlaxEditor.Windows.EditorWindow.OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Editor\Windows\EditorWindow.cs:line 195
   at FlaxEngine.GUI.ContainerControl.OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1162
   at FlaxEngine.GUI.ContainerControl.OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1162
   at FlaxEngine.GUI.ContainerControl.OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1162
   at FlaxEngine.GUI.ContainerControl.OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1162
   at FlaxEngine.GUI.ContainerControl.OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1162
   at FlaxEngine.GUI.ContainerControl.OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1162
   at FlaxEngine.GUI.ContainerControl.OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1162
   at FlaxEngine.GUI.ContainerControl.OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1162
   at FlaxEngine.GUI.ContainerControl.OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1162
   at FlaxEngine.GUI.ContainerControl.OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1162
   at FlaxEngine.Window.Internal_OnKeyDown(KeyboardKeys key) in Z:\Flax\Source\FlaxEngine\Source\Engine\Platform\Window.cs:line 212
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet1`2.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in Z:\Flax\Source\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 256
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in Z:\Flax\Source\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 675
[ 00:00:05.974 ]: [Error] Exception has been thrown during Window.OnKeyDown.
The specified Type must not be a generic type. (Parameter 't')
```

**Comment by mafiesto4** [comment]
Cased by https://github.com/dotnet/runtime/issues/46426
