### ISSUE TITLE
Editor crash when try access null custom asset

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1221]
**Issue description:**
Editor crash if i create a script with a JsonAsset and try acess a null instance of the JsonAsset

Example Code:

```
using FlaxEngine;

namespace Game
{
    [ContentContextMenu("New/My Asset")]
    public class SomeClass
    {
        public float A;
        public float B;
    }

    public class CustomAssetTest : Script
    {
        public JsonAsset Asset;

        public override void OnStart()
        {
            Debug.Log(((SomeClass)Asset.Instance).A);
        }
    }
}
```

**Steps to reproduce:**
* Create a script that acess any variable from (null) instance of JsonAsset
* Crash

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
Did you use Editor build from Launcher or self-build or run Editor from Visual Studio project with C++ debugger? Because C# throws an exception via a native signal which is caught via C++ debugger (due to .NET runtime pl, mono used  different way)

I tested and it correctly rusn with exception print in editor log:
```
[ 00:01:09.169 ]: [Warning] Exception has been thrown. Object reference not set to an instance of an object.
Stack strace:
   at Game.CustomAssetTest.OnStart() in D:\Flax Projects\FlaxSamples\ParticlesFeaturesTour\Source\ParticlesFeaturesTour\ExitOnEsc.cs:line 28
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet0`1.InvokeThunk(Object delegateContext, ManagedHandle instancePtr, IntPtr* paramPtrs) in F:\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 223
   at FlaxEngine.Interop.NativeInterop.ThunkContext.InvokeThunk(ManagedHandle instanceHandle, IntPtr param1, IntPtr param2, IntPtr param3, IntPtr param4, IntPtr param5, IntPtr param6, IntPtr param7) in F:\FlaxEngine\Source\Engine\Engine\NativeInterop.cs:line 1199
[ 00:01:09.176 ]: [Warning] Exception has been thrown.
Object reference not set to an instance of an object.
```

**Comment by RuanLucasGD** [comment]
@mafiesto4 self-build as development mode
