### ISSUE TITLE
Issue with Setting new root in prefab and replacing it

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#1313]
**Issue description:**
I created a prefab from the content folder. I then created a rigid body and a model as children of the root. I then set the rigid body actor as the root and deleted the original root actor (because it is made to be a child of the rigid body once I set the rigid body as root). I then try to save the prefab and get the following error where it will not save. I tried to re create this after starting the prefab over and it did not seem to happen again.

```
[ 00:20:18.796 ]: [Warning] Applying prefab changes with modified root object. Root object id: 259913a848e05b0db2baff8d4f453081, new root: RigidBody (FlaxEngine.RigidBody; dcae01374e71a1ec86ddd0a949612252) (prefab object id: 5f27b88d461481347c2c38818733382d)
[ 00:20:18.796 ]: [Error] Cannot change the prefab root object to the actor that is not yet added to the prefab.
[ 00:20:18.796 ]: [Warning] Exception has been thrown during Window.OnMouseUp. Failed to apply the prefab. See log to learn more.
Stack strace:
   at FlaxEditor.Modules.PrefabsModule.ApplyAll(Actor instance) in Z:\Flax\Source\FlaxEngine\Source\Editor\Modules\PrefabsModule.cs:line 227
   at FlaxEditor.Windows.Assets.PrefabWindow.Save() in Z:\Flax\Source\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.cs:line 351
   at FlaxEditor.GUI.ToolStripButton.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Editor\GUI\ToolStripButton.cs:line 186
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEditor.Windows.Assets.PrefabWindow.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.cs:line 253
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEditor.GUI.Docking.DockPanelProxy.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Editor\GUI\Docking\DockPanelProxy.cs:line 399
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEngine.GUI.SplitPanel.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\Panels\SplitPanel.cs:line 205
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEngine.GUI.SplitPanel.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\Panels\SplitPanel.cs:line 205
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEngine.GUI.SplitPanel.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\Panels\SplitPanel.cs:line 205
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 986
   at FlaxEngine.GUI.WindowRootControl.OnMouseUp(Float2 location, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\UI\GUI\WindowRootControl.cs:line 305
   at FlaxEngine.Window.Internal_OnMouseUp(Float2& mousePos, MouseButton button) in Z:\Flax\Source\FlaxEngine\Source\Engine\Platform\Window.cs:line 242
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet2`3.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in Z:\Flax\Source\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 309
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in Z:\Flax\Source\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 693
[ 00:20:18.796 ]: [Error] Exception has been thrown during Window.OnMouseUp.
Failed to apply the prefab. See log to learn more.

```

**Flax version:**
1.6.6344

**Comment by mafiesto4** [comment]
Prefab sytem supports changing prefab root only if that object already exists in the prefab so Ediotr UI prevents that (eg. prefab must be saved before newly added object can be set as root). Di you save it before using `Set Root` option or have you managed to reroot it somehow manually?

**Comment by Tryibion** [comment]
> Prefab sytem supports changing prefab root only if that object already exists in the prefab so Ediotr UI prevents that (eg. prefab must be saved before newly added object can be set as root). Di you save it before using `Set Root` option or have you managed to reroot it somehow manually?

Maybe my issue was that the asset wasn't saved before I set the new Actor as root. But it let me set the actor as the root and let me continue to make changes to the prefab, but then just wouldn't let me save it. Maybe there needs to be some check the set root function to make sure it is officially part of the prefab?

**Comment by mafiesto4** [comment]
Actually, that's a current limitation of the prefabs system that it needs to save it first before removing/changing root object due to depending on the id of root object.

**Comment by Menotdan** [comment]
> Actually, that's a current limitation of the prefabs system that it needs to save it first before removing/changing root object due to depending on the id of root object.

Maybe we should warn the user, or at least block the action?

**Comment by mafiesto4** [comment]
> Maybe we should warn the user, or at least block the action?

`Set Root` context action in Prefab Scene Tree already prevents from changing the root for actor that has not been saved.

**Comment by Menotdan** [comment]
> `Set Root` context action in Prefab Scene Tree already prevents from changing the root for actor that has not been saved.

Hm, is that earlier comment from Tryibion outdated then? That comment suggested that the check wasn't in place.
