### ISSUE TITLE
Flax Editor crashes when I press the right side Shift or Control keys

### ISSUE THREAD

**Issue by dpalais** [FlaxEngine/FlaxEngine#1321]
**Issue description:**
Flax Editor crashes when I press the right side Shift or Control keys. It works fine with the respective opposite side keys.

**My system is:**
Flax Engine: 1.6.6344
Flax Editor downloaded from flaxengine.com
OS: Debian
Graphical environment: KDE Plasma 5.27 (Wayland session)

**Steps to reproduce:**

1. Create a new project `FlaxEditor -new -project Proj`
2. Press the Right Shift key. The editor crashes.

This is the backtrace:

```
Thread 1 "FlaxEditor-debu" received signal SIGSEGV, Segmentation fault.
0x00007ffff6c41248 in Keyboard::Update(Array<InputDevice::Event, InlinedAllocation<32, HeapAllocation> >&) ()
   from /FlaxEngine/Binaries/Editor/Linux/Debug/libFlaxEditor.so
(gdb) bt
#0  0x00007ffff6c41248 in Keyboard::Update(Array<InputDevice::Event, InlinedAllocation<32, HeapAllocation> >&) ()
   from /FlaxEngine/Binaries/Editor/Linux/Debug/libFlaxEditor.so
#1  0x00007ffff6c4218a in ?? () from /FlaxEngine/Binaries/Editor/Linux/Debug/libFlaxEditor.so
#2  0x00007ffff6e95174 in ?? () from /FlaxEngine/Binaries/Editor/Linux/Debug/libFlaxEditor.so
#3  0x00007ffff6e9bcb7 in Engine::OnUpdate() () from /FlaxEngine/Binaries/Editor/Linux/Debug/libFlaxEditor.so
#4  0x00007ffff6e9ad5f in Engine::Main(char16_t const*) () from /FlaxEngine/Binaries/Editor/Linux/Debug/libFlaxEditor.so
#5  0x000055555555615b in ?? ()
#6  0x00007ffff56321ca in __libc_start_call_main (main=main@entry=0x555555556090, argc=argc@entry=3, argv=argv@entry=0x7fffffffe2d8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#7  0x00007ffff5632285 in __libc_start_main_impl (main=0x555555556090, argc=3, argv=0x7fffffffe2d8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe2c8) at ../csu/libc-start.c:360
#8  0x0000555555555fc5 in ?? ()
```

**Log:**
[Log_2023_08_17_21_25_04.txt](https://github.com/FlaxEngine/FlaxEngine/files/12364826/Log_2023_08_17_21_25_04.txt)

**Comment by mafiesto4** [comment]
Should be fixed in 925b5abb78695b4587f8b1a030a23ff301809152.
