### ISSUE TITLE
Prefab broken if delete model asset.

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1354]
**Issue description:**
If I delete a template asset from my project that is used by a prefab the prefab will broken.

Error:
```
 [Warning] Exception has been thrown during Window.OnUpdate. Index was outside the bounds of the array.
Stack strace:
   at FlaxEditor.CustomEditors.Editors.ModelInstanceEntryEditor.Initialize(LayoutElementsContainer layout) in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\Editors\ModelInstanceEntryEditor.cs:line 27
   at FlaxEditor.CustomEditors.CustomEditor.Initialize(CustomEditorPresenter presenter, LayoutElementsContainer layout, ValueContainer values) in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 130
   at FlaxEditor.CustomEditors.LayoutElementsContainer.Object(ValueContainer values, CustomEditor overrideEditor) in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\LayoutElementsContainer.cs:line 571
   at FlaxEditor.CustomEditors.Editors.CollectionEditor.Initialize(LayoutElementsContainer layout) in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\Editors\CollectionEditor.cs:line 113
   at FlaxEditor.CustomEditors.CustomEditor.Initialize(CustomEditorPresenter presenter, LayoutElementsContainer layout, ValueContainer values) in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 130
   at FlaxEditor.CustomEditors.CustomEditor.RebuildLayout() in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 179
   at FlaxEditor.CustomEditors.Editors.CollectionEditor.Refresh() in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\Editors\CollectionEditor.cs:line 352
   at FlaxEditor.CustomEditors.CustomEditor.RefreshInternal() in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 360
   at FlaxEditor.CustomEditors.CustomEditor.RefreshRootChild() in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 278
   at FlaxEditor.CustomEditors.CustomEditor.RefreshRoot() in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 248
   at FlaxEditor.CustomEditors.CustomEditor.Initialize(CustomEditorPresenter presenter, LayoutElementsContainer layout, ValueContainer values) in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 130
   at FlaxEditor.CustomEditors.CustomEditorPresenter.BuildLayout() in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 367
   at FlaxEditor.CustomEditors.CustomEditorPresenter.OnSelectionChanged() in D:\Dev\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 424
   at FlaxEditor.Windows.Assets.PrefabWindow.OnSelectionChanges() in D:\Dev\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.Selection.cs:line 74
   at FlaxEditor.Windows.Assets.PrefabWindow.OnSelectionChanged(SceneGraphNode[] before) in D:\Dev\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.Selection.cs:line 62
   at FlaxEditor.Windows.Assets.PrefabWindow.Update(Single deltaTime) in D:\Dev\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.cs:line 476
   at FlaxEngine.GUI.ContainerControl.Update(Single deltaTime) in D:\Dev\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 747
   at FlaxEngine.GUI.ContainerControl.Update(Single deltaTime) in D:\Dev\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 747
   at FlaxEngine.GUI.ContainerControl.Update(Single deltaTime) in D:\Dev\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 747
   at FlaxEngine.GUI.RootControl.Update(Single deltaTime) in D:\Dev\FlaxEngine\Source\Engine\UI\GUI\RootControl.cs:line 159
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet1`2.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in D:\Dev\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 326
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in D:\Dev\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 692
[ 00:24:40.531 ]: [Error] Exception has been thrown during Window.OnUpdate.
Index was outside the bounds of the array.

```

**Steps to reproduce:**
1. create a Model Actor on your scene.
2. Create a prefab from your Model Actor.
3. Delete from the project the model asset that is used by prefab.
4. Try open your prefab.
5. Prefab broken

The expected thing was that I could open the prefab even without the template so I could replace it.

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
Fixed in 0a5f983ff4eff7fc2b9bf23ad3f75423e77761ac.
