### ISSUE TITLE
`Particle System` assignment in prefab window for `Particle Effect` seems to be busted

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#1418]
**Issue description:**
Currently, if you would try to assign `Particle System` in a `Particle Effect` through a prefab view window, it would simply refresh while producing this error:
```
[Warning] Error when updating prefab window for S:\SpaceRisk/SpaceRiskGame/Content/Prefabs/Pawns/Player.prefab (Prefab)
[Warning] Exception: Object reference not set to an instance of an object.
[Warning]    at FlaxEditor.CustomEditors.Editors.BooleanEditor.Refresh() in FlaxEngine\Source\Editor\CustomEditors\Editors\BooleanEditor.cs:line 29
   at FlaxEditor.CustomEditors.CustomEditor.RefreshInternal() in FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 360
   at FlaxEditor.CustomEditors.Dedicated.ParticleEffectEditor.RefreshRootChild() in FlaxEngine\Source\Editor\CustomEditors\Dedicated\ParticleEffectEditor.cs:line 114
   at FlaxEditor.CustomEditors.CustomEditor.RefreshRoot() in FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 248
   at FlaxEditor.CustomEditors.SyncPointEditor.RefreshInternal() in FlaxEngine\Source\Editor\CustomEditors\SyncPointEditor.cs:line 90
   at FlaxEditor.CustomEditors.CustomEditorPresenter.PresenterPanel.Update(Single deltaTime) in FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 74
   at FlaxEngine.GUI.ContainerControl.Update(Single deltaTime) in FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 747
   at FlaxEngine.GUI.ContainerControl.Update(Single deltaTime) in FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 747
   at FlaxEngine.GUI.ContainerControl.Update(Single deltaTime) in FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 747
   at FlaxEngine.GUI.ContainerControl.Update(Single deltaTime) in FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 747
   at FlaxEngine.GUI.ContainerControl.Update(Single deltaTime) in FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 747
   at FlaxEditor.Windows.Assets.AssetEditorWindowBase`1.Update(Single deltaTime) in FlaxEngine\Source\Editor\Windows\Assets\AssetEditorWindow.cs:line 366
   at FlaxEditor.Windows.Assets.PrefabWindow.Update(Single deltaTime) in FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.cs:line 476
   ```

**Steps to reproduce:**
1. Create a prefab and add `Particle Effect` in it.
2. Try to assign `Particle System` to this newly created `Particle Effect` through the prefab window.

**Comment by mafiesto4** [comment]
Fixed in #1560
