### ISSUE TITLE
Content window error if you has ContentContextMenu in an class without public constructor

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1838]
**Issue description:**

If you create a script without public constructor and add a **ContentContextMenu**, the ContentWindow don't work throwing erros if you want to create any asset.

Error:
```
[ 00:01:20.595 ]: [Warning] Inner exception. GenericArguments[0], 'MaterialsFeaturesTour.Test', on 'FlaxEditor.Content.SpawnableJsonAssetProxy`1[T]' violates the constraint of type parameter 'T'.
Stack strace:
   at System.RuntimeTypeHandle.Instantiate(QCallTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(RuntimeType inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)

[ 00:01:20.595 ]: [Warning] Exception has been thrown during Window.OnMouseUp. GenericArguments[0], 'MaterialsFeaturesTour.Test', on 'FlaxEditor.Content.SpawnableJsonAssetProxy`1[T]' violates the constraint of type 'T'.
Stack strace:
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at FlaxEditor.Windows.ContentWindow.ShowContextMenuForItem(ContentItem item, Float2& location, Boolean isTreeNode) in /home/capy/Documents/Dev/FlaxEngine/Source/Editor/Windows/ContentWindow.ContextMenu.cs:line 198
   at FlaxEditor.Windows.ContentWindow.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Editor/Windows/ContentWindow.cs:line 1131
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs:line 1002
   at FlaxEditor.GUI.Docking.DockPanelProxy.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Editor/GUI/Docking/DockPanelProxy.cs:line 405
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs:line 1002
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs:line 1002
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs:line 1002
   at FlaxEngine.GUI.SplitPanel.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/Panels/SplitPanel.cs:line 205
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs:line 1002
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs:line 1002
   at FlaxEngine.GUI.SplitPanel.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/Panels/SplitPanel.cs:line 205
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs:line 1002
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs:line 1002
   at FlaxEngine.GUI.WindowRootControl.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/WindowRootControl.cs:line 305
   at FlaxEngine.Window.Internal_OnMouseUp(Float2& mousePos, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/Platform/Window.cs:line 242
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet2`3.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/Engine/NativeInterop.Invoker.cs:line 387
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/Engine/NativeInterop.Unmanaged.cs:line 746
[ 00:01:20.595 ]: [Error] Exception has been thrown during Window.OnMouseUp.
GenericArguments[0], 'MaterialsFeaturesTour.Test', on 'FlaxEditor.Content.SpawnableJsonAssetProxy`1[T]' violates the constraint of type 'T'.
```

**Steps to reproduce:**
Create this script and try create any asset using your ContentWindow:

```
[ContentContextMenu("New/Test")]
public class Test
{
    private Test(int a, int b)
    {

    }
}
```

**Flax version:**
1.7 master

**Comment by mafiesto4** [comment]
Fixed in 0d85094ebb933f34364f71d02afb879a7f017b8f + 22d754e7972fb7c51382e928a2642d7414da8e29.
