### ISSUE TITLE
UI Slider Deserialization throws out of Range Error if Min is greater than default max.

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1853]
**Issue description:**
If the minimum value is set to a greater value than the default 100 maximum, the slider throws a deserialization error.
Looks like a deserialization order issue.

**Steps to reproduce:**
1. Create Slider
2. Set Maximum Value to 1000
3. Set Minimum Value to 500
4. Save
5. Press Play

```
[ 00:00:32.241 ]: [Warning] Inner exception. Specified argument was out of the range of valid values.
Stack strace:
   at FlaxEngine.GUI.Slider.set_Minimum(Single value) in D:\FlaxEngineLW\Source\Engine\UI\GUI\Common\Slider.cs:line 30
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value) in F:\FlaxEngineDotnet\Cache\Intermediate\Deps\NewtonsoftJson\Src\Newtonsoft.Json\Serialization\ExpressionValueProvider.cs:line 93

[ 00:00:32.241 ]: [Warning] Exception has been thrown during UIControl::Deserialize. Error setting value to 'Minimum' on 'FlaxEngine.GUI.Slider'.
Stack strace:
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value) in F:\FlaxEngineDotnet\Cache\Intermediate\Deps\NewtonsoftJson\Src\Newtonsoft.Json\Serialization\ExpressionValueProvider.cs:line 93
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) in F:\FlaxEngineDotnet\Cache\Intermediate\Deps\NewtonsoftJson\Src\Newtonsoft.Json\Serialization\JsonSerializerInternalReader.cs:line 1091
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) in F:\FlaxEngineDotnet\Cache\Intermediate\Deps\NewtonsoftJson\Src\Newtonsoft.Json\Serialization\JsonSerializerInternalReader.cs:line 2526
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target) in F:\FlaxEngineDotnet\Cache\Intermediate\Deps\NewtonsoftJson\Src\Newtonsoft.Json\Serialization\JsonSerializerInternalReader.cs:line 116
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target) in F:\FlaxEngineDotnet\Cache\Intermediate\Deps\NewtonsoftJson\Src\Newtonsoft.Json\JsonSerializer.cs:line 824
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target) in F:\FlaxEngineDotnet\Cache\Intermediate\Deps\NewtonsoftJson\Src\Newtonsoft.Json\JsonSerializer.cs:line 797
   at FlaxEngine.Json.JsonSerializer.Deserialize(Object input, String json) in D:\FlaxEngineLW\Source\Engine\Serialization\JsonSerializer.cs:line 226
   at FlaxEngine.UIControl.Deserialize(String json, Type controlType) in D:\FlaxEngineLW\Source\Engine\UI\UIControl.cs:line 403
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet2`3.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in D:\FlaxEngineLW\Source\Engine\Engine\NativeInterop.Invoker.cs:line 375
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in D:\FlaxEngineLW\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 746
[ 00:00:32.241 ]: [Error] Exception has been thrown during UIControl::Deserialize.
Error setting value to 'Minimum' on 'FlaxEngine.GUI.Slider'.
```

**Flax version:**
1.7 Large Worlds

**Comment by Tryibion** [comment]
It is working as it is coded. if the minimum is set greater than the maximum it will throw an our of range exception. When the code deserializes, it is setting the minimum value and throwing that error as it should. If it shouldnt do this, what would be the expected behavior? maybe caping the minimum to not go above the maximum and the maximum to not go below the minimum?

**Comment by schmidt-florian** [comment]
Sorry, I forgot to describe a step >_>
I have added Step 2.

**Comment by mafiesto4** [comment]
Fixedin #1871.
