### ISSUE TITLE
NUnit tests are not being run on windows

### ISSUE THREAD

**Issue by SinnersSum** [FlaxEngine/FlaxEngine#1892]
Tests on windows appear to be silently failing. Across all PRs to FlaxEngine a routine entry appears in the workflow test logs reading;
```
Microsoft (R) Test Execution Command Line Tool Version 17.7.2 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process for source(s) 'D:\a\FlaxEngine\FlaxEngine\Binaries\Tests\Flax.Build.Tests.dll' exited with error: A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'D:\a\FlaxEngine\FlaxEngine\Binaries\Tests\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'D:\a\FlaxEngine\FlaxEngine\Binaries\Tests\testhost.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'D:\a\FlaxEngine\FlaxEngine\Binaries\Tests\testhost.runtimeconfig.json' file and specify the appropriate framework.
. Please check the diagnostic logs for more information.

Test Run Aborted.
Binaries\Editor\Win64\Development\FlaxEngine.CSharp.dll
1 File(s) copied
Binaries\Editor\Win64\Development\FlaxEngine.CSharp.runtimeconfig.json
1 File(s) copied
Binaries\Editor\Win64\Development\Newtonsoft.Json.dll
1 File(s) copied
Microsoft (R) Test Execution Command Line Tool Version 17.7.2 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No test is available in D:\a\FlaxEngine\FlaxEngine\Binaries\Tests\FlaxEngine.CSharp.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

In my own recent PR this same entry shows up at the end of [the test log](https://github.com/FlaxEngine/FlaxEngine/actions/runs/6779256958/job/18438397638?pr=1888#step:7:1030). The error reported by the linux tests is legitimate —there is actually a bug in my code— but it appears that the windows tests aren't even being run.

Additionally this is causing serious problems for me in my attempt to hunt the bug down, as [the failing tests](https://github.com/FlaxEngine/FlaxEngine/tree/d6e93a7fab1544c50b02242e42d37dabfcc09d66/Source/Engine/Tests) cannot be easily run. Attempting to run them through the VS interface produces a similar error;

```
Building Test Projects
Starting test discovery for requested test run
========== Starting test discovery ==========
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
========== Test discovery aborted: 0 Tests found in 6 ms ==========
```

I have been able to get them to run through the dotnet CLI, but this precludes actually debugging them.

**Comment by mafiesto4** [comment]
This has been fixed sometime ago (for 1.10 I think).
