### ISSUE TITLE
Intermediate Editor Crashes when using ImGUI

### ISSUE THREAD

**Issue by KyuubiYoru** [FlaxEngine/FlaxEngine#1901]
**Issue description:**
The editor crashes intermittently when entering play mode, particularly after making changes to C# scripts. The crashes are not consistently reproducible but seem to be more frequent following script modifications. 

`Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at ImGui.<Internal_Begin1>g____PInvoke|99_0(IntPtr, ImGuiWindowFlags)
--------------------------------
   at ImGui.Internal_Begin1(System.String, ImGuiWindowFlags)
   at ImGui.Begin(System.String, ImGuiWindowFlags)
   at GameNetworkManager.DrawImGui()
   at GameNetworkManager.OnUpdate()
   at FlaxEngine.Interop.NativeInterop+Invoker+InvokerNoRet0`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InvokeThunk(System.Object, FlaxEngine.Interop.ManagedHandle, IntPtr*)
   at FlaxEngine.Interop.NativeInterop+ThunkContext.InvokeThunk(FlaxEngine.Interop.ManagedHandle, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr)`

**Flax version:**
b3c15d656215e5b7265c7dc30ad16d529d3df14d

**Comment by mafiesto4** [comment]
Most likely fixed in https://github.com/FlaxEngine/ImGui/commit/951602db071ac81b3390bb2c59ae1bec0a4a1b4a. Can you confirm this?

**Comment by KyuubiYoru** [comment]
Had one crash, but wasn't running Flax from the IDE so i don't have a stack trace.
But worked now 1 hour without a crash so it seems to be fixed.
