### ISSUE TITLE
Error on apply changes on prefab when replace missing script

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1995]
**Issue description:**
I cannot replace the script of my prefab in the scene.

https://github.com/FlaxEngine/FlaxEngine/assets/79365912/7d1b967d-3a74-4f10-b845-37d3a4bcab00

Error:

```

[ 00:00:59.373 ]: [Warning] Missing object 08dbee6e9e8ec1e612a95f35cf538352 in prefab FlaxEngine.Prefab, 08dbee6e9e8fe88512a95f70cf5385a1, /home/capy/Documents/Dev/FlaxSamples-master/BasicTemplate/Content/EmptyActor.prefab.
[ 00:00:59.397 ]: [Warning] One of the target instance objects has link to prefab object that does not exist in prefab.
[ 00:00:59.476 ]: [Warning] Exception has been thrown during Window.OnMouseUp. Failed to apply the prefab. See log to learn more.
Stack strace:
   at FlaxEditor.Modules.PrefabsModule.ApplyAll(Actor instance) in /home/capy/Documents/Dev/FlaxEngine/Source/Editor/Modules/PrefabsModule.cs:line 230
   at FlaxEditor.CustomEditors.Dedicated.ActorEditor.OnDiffApplyAll() in /home/capy/Documents/Dev/FlaxEngine/Source/Editor/CustomEditors/Dedicated/ActorEditor.cs:line 352
   at FlaxEditor.GUI.PrefabDiffContextMenu.OnApplyAllClicked() in /home/capy/Documents/Dev/FlaxEngine/Source/Editor/GUI/PrefabDiffContextMenu.cs:line 83
   at FlaxEngine.GUI.Button.OnClick() in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/Common/Button.cs:line 184
   at FlaxEngine.GUI.Button.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/Common/Button.cs:line 311
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs:line 1002
   at FlaxEditor.GUI.ContextMenu.ContextMenuBase.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Editor/GUI/ContextMenu/ContextMenuBase.cs:line 519
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs:line 1002
   at FlaxEngine.GUI.WindowRootControl.OnMouseUp(Float2 location, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/UI/GUI/WindowRootControl.cs:line 305
   at FlaxEngine.Window.Internal_OnMouseUp(Float2& mousePos, MouseButton button) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/Platform/Window.cs:line 242
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet2`3.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/Engine/NativeInterop.Invoker.cs:line 387
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in /home/capy/Documents/Dev/FlaxEngine/Source/Engine/Engine/NativeInterop.Unmanaged.cs:line 746
[ 00:00:59.476 ]: [Error] Exception has been thrown during Window.OnMouseUp.
Failed to apply the prefab. See log to learn more.

```

**Steps to reproduce:**
1. Create a prefab
2. Add it in your scene
3. Add script to prefab
4. Apply changes
5. Change script name
6. try replace script on the prefab
7. try apply changes
8. error

**Minimal reproduction project:**
any

**Flax version:**
1.7 master

**Comment by mafiesto4** [comment]
Fixed in 2d5d001a4491fbcbc870cfdaa3880b5da5a15aad and 470c108ed9cea1194f0f122abc86e177bf3ed658
