### ISSUE TITLE
Larg FBX files import Brackes the engine. 

### ISSUE THREAD

**Issue by JackRumboll** [FlaxEngine/FlaxEngine#2370]
**Issue Description:**

I was importing an FBX with the default settings the FBX was 1.2GB and it had a lot of models in it about 1M models 

I don't know if there are any log files because the engine closed but if there are just let me know where I can find them so I can add them.

**Steps to reproduce:**

Just import a large FBX with a lot of smaller models in.

**Flax version:**

1.7
1.8

**Comment by Menotdan** [comment]
The logs are at `<ProjectFolder>/Logs`.

**Comment by JackRumboll** [comment]
![image](https://github.com/FlaxEngine/FlaxEngine/assets/113502547/66da3b8e-828b-4fef-b445-2d0f39ef2834)
[Log_2024_02_13_09_31_23.txt](https://github.com/FlaxEngine/FlaxEngine/files/14769331/Log_2024_02_13_09_31_23.txt)
[Log_2024_03_27_08_53_02.txt](https://github.com/FlaxEngine/FlaxEngine/files/14769333/Log_2024_03_27_08_53_02.txt)

**Comment by Menotdan** [comment]
> Here are the settings and the logs for importing the model.
> 
> ![image](https://private-user-images.githubusercontent.com/113502547/317162961-66da3b8e-828b-4fef-b445-2d0f39ef2834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjMzMDcsIm5iZiI6MTcxMTUyMzAwNywicGF0aCI6Ii8xMTM1MDI1NDcvMzE3MTYyOTYxLTY2ZGEzYjhlLTgyOGItNGZlZi1iNDQ1LTJkMGYzOWVmMjgzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNzAzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWMzNjlkMGUwNjBkYjdlZWQxZDM4MWRjNmU2NjE0ZTAzOGVmMDk3ZTNlNmEzZmIyYTBlNzUyY2JiYWYzZGE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DntcPXFnqvZGlY3HJneaFTGwIcSMLNO_DHIBukaa6_c) [Log_2024_02_13_09_31_23.txt](https://github.com/FlaxEngine/FlaxEngine/files/14769331/Log_2024_02_13_09_31_23.txt) [Log_2024_03_27_08_53_02.txt](https://github.com/FlaxEngine/FlaxEngine/files/14769333/Log_2024_03_27_08_53_02.txt)

Is the result different if you uncheck "Import Textures"? The log seems to stop suddenly after or during texture imports.

**Comment by JackRumboll** [comment]
new settings and it works if I merge the model but if I don't merge the model then it breaks. 

![image](https://github.com/FlaxEngine/FlaxEngine/assets/113502547/c28bfa9a-cd02-40ca-8830-deb66abc855e)
[Log_2024_03_27_09_06_59.txt](https://github.com/FlaxEngine/FlaxEngine/files/14769463/Log_2024_03_27_09_06_59.txt)

**Comment by Menotdan** [comment]
```
[Warning] Exception: The process cannot access the file 'Material #141992 Slot #1.flax' because it is being used by another process.
[ 00:06:05.540 ]: [Warning]    at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at FlaxEditor.Modules.ContentDatabaseModule.Delete(ContentItem item, Boolean deletedByUser) in Source\Editor\Modules\ContentDatabaseModule.cs:line 689
```
I see this exception, I wonder if it's related.

**Comment by JackRumboll** [comment]
here is a frech loge file where i only imported the modle 
[Log_2024_03_27_09_20_44.txt](https://github.com/FlaxEngine/FlaxEngine/files/14769539/Log_2024_03_27_09_20_44.txt)

**Comment by JackRumboll** [comment]
this what bug i get when i attach VS code to the engine and then importing.

in the skript LibraryImports.g.cs i think
![image](https://github.com/FlaxEngine/FlaxEngine/assets/113502547/5c38a112-1270-400e-a2de-835c9f680619)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/113502547/0b96a932-529f-45af-8b86-f25ba96c676a)

**Comment by Menotdan** [comment]
> this what bug i get when i attach VS code to the engine and then importing.

Can you share the callstack? Also it's weird that it's failing to marshal the return value..

**Comment by JackRumboll** [comment]
Are you talking about this?

![image](https://github.com/FlaxEngine/FlaxEngine/assets/113502547/af0cb0c7-8cd5-4c17-8897-6bf2462f4079)
