### ISSUE TITLE
Spline as Prefab throws null ref

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#2383]
**Issue Description:**

I have created a spline rope, played a bit around, and finally made it to a prefab.
Then i tried to open the attached prefab in the prefab editor, the editor throws this error:

```
[ 00:00:08.067 ]: [Warning] Error when updating prefab window for D:\Projects/Flax/Test Blank/Content/Rope.prefab (Prefab)
[ 00:00:08.067 ]: [Warning] Exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
[ 00:00:08.067 ]: [Warning]    at System.Collections.Generic.List`1.get_Item(Int32 index)
   at FlaxEditor.CustomEditors.Dedicated.SplineEditor.UpdateSelectedPoint() in F:\FlaxEngine\Source\Editor\CustomEditors\Dedicated\SplineEditor.cs:line 515
   at FlaxEditor.CustomEditors.Dedicated.SplineEditor.Refresh() in F:\FlaxEngine\Source\Editor\CustomEditors\Dedicated\SplineEditor.cs:line 346
   at FlaxEditor.CustomEditors.CustomEditor.Initialize(CustomEditorPresenter presenter, LayoutElementsContainer layout, ValueContainer values) in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 125
   at FlaxEditor.CustomEditors.Editors.GenericEditor.Initialize(CustomEditorPresenter presenter, LayoutElementsContainer layout, ValueContainer values) in F:\FlaxEngine\Source\Editor\CustomEditors\Editors\GenericEditor.cs:line 677
   at FlaxEditor.CustomEditors.CustomEditorPresenter.RootEditor.Initialize(LayoutElementsContainer layout) in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 181
   at FlaxEditor.CustomEditors.CustomEditor.Initialize(CustomEditorPresenter presenter, LayoutElementsContainer layout, ValueContainer values) in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 124
   at FlaxEditor.CustomEditors.CustomEditorPresenter.RootEditor.Setup(CustomEditorPresenter presenter) in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 157
   at FlaxEditor.CustomEditors.CustomEditorPresenter.BuildLayout() in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 400
   at FlaxEditor.CustomEditors.CustomEditorPresenter.OnSelectionChanged() in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 476
   at FlaxEditor.CustomEditors.CustomEditorPresenter.Select(IEnumerable`1 objects) in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 371
   at FlaxEditor.Windows.Assets.PrefabWindow.OnSelectionChanges() in F:\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.Selection.cs:line 108
   at FlaxEditor.Windows.Assets.PrefabWindow.OnSelectionChanged(SceneGraphNode[] before) in F:\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.Selection.cs:line 59
   at FlaxEditor.Windows.Assets.PrefabWindow.Select(SceneGraphNode node, Boolean additive) in F:\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.Selection.cs:line 163
   at FlaxEditor.Windows.Assets.PrefabWindow.OnPrefabOpened() in F:\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.cs:line 350
   at FlaxEditor.Windows.Assets.PrefabWindow.OnAssetLoaded() in F:\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.cs:line 425
   at FlaxEditor.Windows.Assets.AssetEditorWindowBase`1.Update(Single deltaTime) in F:\FlaxEngine\Source\Editor\Windows\Assets\AssetEditorWindow.cs:line 375
   at FlaxEditor.Windows.Assets.PrefabWindow.Update(Single deltaTime) in F:\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.cs:line 457
[ 00:00:08.073 ]: [Warning] Exception has been thrown during Window.OnUpdate. Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Stack strace:
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at FlaxEditor.CustomEditors.Dedicated.SplineEditor.UpdateSelectedPoint() in F:\FlaxEngine\Source\Editor\CustomEditors\Dedicated\SplineEditor.cs:line 515
   at FlaxEditor.CustomEditors.Dedicated.SplineEditor.Refresh() in F:\FlaxEngine\Source\Editor\CustomEditors\Dedicated\SplineEditor.cs:line 346
   at FlaxEditor.CustomEditors.CustomEditor.Initialize(CustomEditorPresenter presenter, LayoutElementsContainer layout, ValueContainer values) in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 125
   at FlaxEditor.CustomEditors.Editors.GenericEditor.Initialize(CustomEditorPresenter presenter, LayoutElementsContainer layout, ValueContainer values) in F:\FlaxEngine\Source\Editor\CustomEditors\Editors\GenericEditor.cs:line 677
   at FlaxEditor.CustomEditors.CustomEditorPresenter.RootEditor.Initialize(LayoutElementsContainer layout) in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 181
   at FlaxEditor.CustomEditors.CustomEditor.Initialize(CustomEditorPresenter presenter, LayoutElementsContainer layout, ValueContainer values) in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 124
   at FlaxEditor.CustomEditors.CustomEditorPresenter.RootEditor.Setup(CustomEditorPresenter presenter) in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 157
   at FlaxEditor.CustomEditors.CustomEditorPresenter.BuildLayout() in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 400
   at FlaxEditor.CustomEditors.CustomEditorPresenter.OnSelectionChanged() in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 476
   at FlaxEditor.CustomEditors.CustomEditorPresenter.Select(IEnumerable`1 objects) in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 371
   at FlaxEditor.Windows.Assets.PrefabWindow.OnSelectionChanges() in F:\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.Selection.cs:line 108
   at FlaxEditor.Windows.Assets.PrefabWindow.OnSelectionChanged(SceneGraphNode[] before) in F:\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.Selection.cs:line 59
   at FlaxEditor.Windows.Assets.PrefabWindow.Select(SceneGraphNode node, Boolean additive) in F:\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.Selection.cs:line 163
   at FlaxEditor.Windows.Assets.PrefabWindow.OnPrefabOpened() in F:\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.cs:line 350
   at FlaxEditor.Windows.Assets.PrefabWindow.Update(Single deltaTime) in F:\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.cs:line 471
   at FlaxEngine.GUI.ContainerControl.Update(Single deltaTime) in F:\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 765
   at FlaxEngine.GUI.ContainerControl.Update(Single deltaTime) in F:\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 765
   at FlaxEngine.GUI.RootControl.Update(Single deltaTime) in F:\FlaxEngine\Source\Engine\UI\GUI\RootControl.cs:line 131
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet1`2.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in F:\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 334
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in F:\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 754
[ 00:00:08.073 ]: [Error] Exception has been thrown during Window.OnUpdate.
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
[ 00:00:08.096 ]: [Warning] Exception has been thrown. Object reference not set to an instance of an object.
Stack strace:
   at FlaxEngine.Interop.NativeInterop.RaiseException(ManagedHandle exceptionHandle) in F:\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 714
   at FlaxEngine.Spline.Internal_GetSplinePointsCount(IntPtr __obj)
   at FlaxEngine.Spline.get_SplinePointsCount() in F:\FlaxEngine\Cache\Intermediate\FlaxEditor\Windows\x64\Development\Level\Level.Bindings.Gen.cs:line 6261
   at FlaxEditor.SceneGraph.Actors.SplineNode.SyncSplineKeyframeWithNodes() in F:\FlaxEngine\Source\Editor\SceneGraph\Actors\SplineNode.cs:line 329
   at FlaxEditor.SceneGraph.Actors.SplineNode.OnUpdate() in F:\FlaxEngine\Source\Editor\SceneGraph\Actors\SplineNode.cs:line 323
   at FlaxEngine.Scripting.Internal_Update() in F:\FlaxEngine\Source\Engine\Scripting\Scripting.cs:line 315
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerStaticNoRet0.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in F:\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 566
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in F:\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 754
[ 00:00:08.096 ]: [Warning] Exception has been thrown.
Object reference not set to an instance of an object.
```

**Minimal reproduction file:**

[Rope.zip](https://github.com/FlaxEngine/FlaxEngine/files/14817340/Rope.zip)

**Flax version:**

1.8

**Comment by mafiesto4** [comment]
Fixed in 7578e1dbe393048795bb087586dbfba9c84a5ec8,
