### ISSUE TITLE
Unable to save Prefab after changing static flags in a child actor

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#2384]
**Issue description:**

I cannot save a prefab where I changed the static flags of a child actor.
I also tried to save the changes via the prefab in the scene and apply changes. Throws also the error.

This throws the following error:

```
[ 01:20:38.750 ]: [Warning] Exception has been thrown during Window.OnMouseUp. Object reference not set to an instance of an object.
Stack strace:
   at FlaxEditor.CustomEditors.CustomEditor.ClearReferenceValueAll() in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 539
   at FlaxEditor.CustomEditors.Dedicated.ActorEditor.OnPrefabApplying(Prefab prefab, Actor instance) in F:\FlaxEngine\Source\Editor\CustomEditors\Dedicated\ActorEditor.cs:line 186
   at FlaxEditor.Modules.PrefabsModule.ApplyAll(Actor instance) in F:\FlaxEngine\Source\Editor\Modules\PrefabsModule.cs:line 226
   at FlaxEditor.CustomEditors.Dedicated.ActorEditor.OnDiffApplyAll() in F:\FlaxEngine\Source\Editor\CustomEditors\Dedicated\ActorEditor.cs:line 354
   at FlaxEditor.GUI.PrefabDiffContextMenu.OnApplyAllClicked() in F:\FlaxEngine\Source\Editor\GUI\PrefabDiffContextMenu.cs:line 84
   at FlaxEngine.GUI.Button.OnClick() in F:\FlaxEngine\Source\Engine\UI\GUI\Common\Button.cs:line 184
   at FlaxEngine.GUI.Button.OnMouseUp(Float2 location, MouseButton button) in F:\FlaxEngine\Source\Engine\UI\GUI\Common\Button.cs:line 311
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in F:\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1029
   at FlaxEditor.GUI.ContextMenu.ContextMenuBase.OnMouseUp(Float2 location, MouseButton button) in F:\FlaxEngine\Source\Editor\GUI\ContextMenu\ContextMenuBase.cs:line 519
   at FlaxEngine.Window.Internal_OnMouseUp(Float2& mousePos, MouseButton button) in F:\FlaxEngine\Source\Engine\Platform\Window.cs:line 242
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet2`3.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in F:\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 387
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in F:\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 754
[ 01:20:38.750 ]: [Error] Exception has been thrown during Window.OnMouseUp.
Object reference not set to an instance of an object.

```

The Prefab is a recreation of the prefab in #2383.
After recreation, I do not have the error of #2383, BUT if I try to copy that new prefab to a test project, the error of #2383 is thrown again, even if it worked in the main project. So, this error could be fixed with #2383.
However, due to this, I can not recreate this issue in a blank project. 

Nonetheless, I will also attach the newly created prefab here. This error may still be persistent after the other one has been fixed.

**Steps to reproduce:**

1. Open Prefab
2. Select Child Actor "End Point"
3. Set Static Flags to None
4. Try to save -> Error Occurs

**Minimal reproduction project:**

[New Rope.zip](https://github.com/FlaxEngine/FlaxEngine/files/14817392/Rope.zip)

**Flax version:**

1.8

**Comment by mafiesto4** [comment]
Fixed in a83b589e12438c8d900a14a8f9731b949e24835f.
