### ISSUE TITLE
[C++] Adding empty one-line-comment at the end of a API_FIELD() definition fails to compile

### ISSUE THREAD

**Issue by Vizepi** [FlaxEngine/FlaxEngine#265]
**Issue description:**
When using the macro API_FIELD(), Flax.Build generates bindings for C#. This task fails if the line containing the API_FIELD() macro has an empty comment at the end:
`API_FIELD() float _var = 1.0f;` compiles fine and binding generation succeed.
`API_FIELD() float _var = 1.0f; //` compiles fine but the C# binding fails. The error is the following:

```
startindex cannot be larger than length of string.
at System.String.Substring(Int32 startIndex, Int32 length)
at Flax.Build.Bindings.BindingsGenerator.GenerateCSharpAttributes(BuildData buildData, StringBuilder contents, String indent, String attributes, String[] comment, Boolean canUseTooltip, Boolean useUnmanaged) in C:\FlaxEngine\Source\Tools\Flax.Build\Bindings\BindingsGenerator.CSharp.cs:line 412
at Flax.Build.Bindings.BindingsGenerator.GenerateCSharpClass(BuildData buildData, StringBuilder contents, String indent, ClassInfo classInfo) in C:\FlaxEngine\Source\Tools\Flax.Build\Bindings\BindingsGenerator.CSharp.cs:line 590
at Flax.Build.Bindings.BindingsGenerator.GenerateCSharpType(BuildData buildData, StringBuilder contents, String indent, Object type) in C:\FlaxEngine\Source\Tools\Flax.Build\Bindings\BindingsGenerator.CSharp.cs:line 965
at Flax.Build.Bindings.BindingsGenerator.GenerateCSharp(BuildData buildData, ModuleInfo moduleInfo, BindingsResult& bindings) in C:\FlaxEngine\Source\Tools\Flax.Build\Bindings\BindingsGenerator.CSharp.cs:line 1016
at Flax.Build.Bindings.BindingsGenerator.GenerateBindings(BuildData buildData, Module module, BuildOptions& moduleOptions, BindingsResult& bindings) in C:\FlaxEngine\Source\Tools\Flax.Build\Bindings\BindingsGenerator.cs:line 464
at Flax.Build.Builder.BuildModuleInner(BuildData buildData, Module module, BuildOptions moduleOptions) in C:\FlaxEngine\Source\Tools\Flax.Build\Build\NativeCpp\Builder.NativeCpp.cs:line 341
at Flax.Build.Builder.BuildModule(BuildData buildData, Module module) in C:\FlaxEngine\Source\Tools\Flax.Build\Build\NativeCpp\Builder.NativeCpp.cs:line 256
at Flax.Build.Builder.BuildTargetNativeCpp(RulesAssembly rules, TaskGraph graph, Target target, Dictionary`2 buildContext, Toolchain toolchain, TargetConfiguration configuration, Boolean isBuildingReference, Boolean skipBuild) in C:\FlaxEngine\Source\Tools\Flax.Build\Build\NativeCpp\Builder.NativeCpp.cs:line 729
at Flax.Build.Builder.BuildTargets() in C:\FlaxEngine\Source\Tools\Flax.Build\Build\Builder.cs:line 199
at Flax.Build.Program.Main() in C:\FlaxEngine\Source\Tools\Flax.Build\Program.cs:line 125
```

**Steps to reproduce:**
- Create a C++ script
- Add this line in the generated class: `API_FIELD() float _var = 1.0f; //`
- Compile or go to editor
- See in output that C# binding generation failed

**Flax version:**
master @ 6987834b2dd8343ed13f63c0bfd51614af6048bf

**Comment by mafiesto4** [comment]
From the stack trace, it looks like it was caused by the tooltip generation issue. Should work fine now.
