### ISSUE TITLE
Spline options error if Large Worlds is enabled

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#2709]
**Issue description:**
I can't use these options if large worlds is enabled.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/167662176/2b89dcce-9a84-4b32-915b-ea5764d03745)

```
[ 00:00:24.994 ]: [Warning] Failed to setup values and UI for item SplineKeyframes
[ 00:00:24.994 ]: [Warning] Exception has been thrown by the target of an invocation.
[ 00:00:25.009 ]: [Warning]    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at FlaxEditor.Scripting.ScriptMemberInfo.GetValue(Object obj) in C:\Dev\FlaxEngine\Source\Editor\Scripting\ScriptType.cs:line 661
   at FlaxEditor.CustomEditors.ValueContainer..ctor(ScriptMemberInfo info, ValueContainer instanceValues) in C:\Dev\FlaxEngine\Source\Editor\CustomEditors\Values\ValueContainer.cs:line 261
   at FlaxEditor.CustomEditors.Editors.GenericEditor.ItemInfo.GetValues(ValueContainer instanceValues) in C:\Dev\FlaxEngine\Source\Editor\CustomEditors\Editors\GenericEditor.cs:line 149
   at FlaxEditor.CustomEditors.Editors.GenericEditor.Initialize(LayoutElementsContainer layout) in C:\Dev\FlaxEngine\Source\Editor\CustomEditors\Editors\GenericEditor.cs:line 806

```

**Flax version:**
[master](https://github.com/FlaxEngine/FlaxEngine/commit/f52059522b524daddb1ad2659647d41db8ff2496)

**Comment by mafiesto4** [comment]
Fixed in 075c224022d107a60715709c9662fe3b9fceb0f3,
