### ISSUE TITLE
Unexpected warning reference for F:\FlaxEngine\...

### ISSUE THREAD

**Issue by AlTheSlacker** [FlaxEngine/FlaxEngine#2935]
**Version**
1.8.2 as downloaded by the Flax Engine tool as the latest build. Run on Win10.

**Issue description:**
Due to my bad code I tripped an output warning:

[ 00:21:55.371 ]: [Warning] Exception: Invalid value type <null>.
[ 00:21:55.371 ]: [Warning]    at FlaxEditor.CustomEditors.Editors.FloatEditor.Refresh() in F:\FlaxEngine\Source\Editor\CustomEditors\Editors\FloatEditor.cs:line 96
   at FlaxEditor.CustomEditors.CustomEditor.RefreshInternal() in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 335
   at FlaxEditor.CustomEditors.CustomEditor.RefreshInternal() in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 347
   at FlaxEditor.CustomEditors.CustomEditor.RefreshRootChild() in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 282
   at FlaxEditor.CustomEditors.CustomEditor.RefreshRoot() in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 243
   at FlaxEditor.CustomEditors.SyncPointEditor.RefreshInternal() in F:\FlaxEngine\Source\Editor\CustomEditors\SyncPointEditor.cs:line 85
   at FlaxEditor.CustomEditors.CustomEditorPresenter.PresenterPanel.Update(Single deltaTime) in F:\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 91

But I do not have FlaxEngine installed in any location that looks anything like that. I assume it is tied to the original build directories of whoever compiled the release version of 1.8.2. Whilst the null trap is correct, the path is somewhat confusing "F:\FlaxEngine\Source\Editor\CustomEditors\"

**Steps to reproduce:**
Due to my code structure it is not trivial for me to construct a replicator. If one is absolutely needed to resolve this, please reply here and I will add one.

**Minimal reproduction project:**
See above.

**Comment by mafiesto4** [comment]
Could you at least post a sample code of actor/script that triggered this error when selected? Because it looks like `Float` value editor got incorrect data type and threw an exception.

**Comment by AlTheSlacker** [comment]
I'm sure I messed up the float value, it was just the error message referring to a non-existent location that I was pointing out. I'll try and make a reproducer in the next few days, this is non-trivial as the error occurs when a monitoring process of mine attempts to update a field based on other external factors, it's not just one actor running some code.

**Comment by AlTheSlacker** [comment]
[FlaxBug_1.zip](https://github.com/user-attachments/files/17058509/FlaxBug_1.zip)

Apologies, I have had to send you a minimal version of the project as the code dependencies are awkward to pull apart. The scene should open containing a small tree of actors: <mujoco> Default - <default> - <general>. If you click <general> and check properties you will see warning with one entry labelled "key" double click "key" and and change the name to something else, the output log will then show the warnings.

I have rewritten my project to use List<float> and the problem has gone away, so this is merely if you want to pursue the error message. I'm sorry I can't get a simpler reproducer together.
