### ISSUE TITLE
Warning spam, resulting in a ~2GB log file that is 10,114,022 lines long (lol)

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2980]
**Issue description:**

I had the editor open, one panel docked out on my second screen while I was watching a youtube video.
Suddenly I saw the window on my second screen close, so I figured that Flax must have crashed.
I wanted to know why it crashed, so I took a look at the Logs folder and saw a ~2GB big log file.

The thing that makes it so big is a spam of 
```
[ 02:15:25.625 ]: [Warning] Exception has been thrown. Exception has been thrown by the target of an invocation.
Stack strace:
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at FlaxEngine.Interop.NativeInterop.ThunkContext.InvokeThunk(ManagedHandle instanceHandle, IntPtr param1, IntPtr param2, IntPtr param3, IntPtr param4, IntPtr param5, IntPtr param6, IntPtr param7) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.cs:line 1846
[ 02:15:25.625 ]: [Warning] Exception has been thrown.
Exception has been thrown by the target of an invocation.
[ 02:15:25.625 ]: [Warning] Inner exception. Object reference not set to an instance of an object.
Stack strace:
   at FlaxEngine.Interop.NativeInterop.RaiseException(ManagedHandle exceptionHandle) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 766
   at FlaxEngine.Actor.<Internal_GetTransform>g____PInvoke|65_0(IntPtr ____obj_native, Transform* ____resultAsRef_native)
   at FlaxEngine.UICanvas.GetWorldMatrix(Vector3 viewOrigin, Matrix& world) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\UICanvas.cs:line 378
   at FlaxEngine.UICanvas.GetWorldMatrix(Matrix& world) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\UICanvas.cs:line 368
   at FlaxEngine.UICanvas.get_Bounds() in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\UICanvas.cs:line 344
   at FlaxEngine.CanvasRenderer.Render(GPUContext context, RenderContext& renderContext, GPUTexture input, GPUTexture output) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\UICanvas.cs:line 71
   at InvokeStub_CanvasRenderer.Render(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```
I had that happen to me before, which resulted in the text in the Outpug Log panel becoming misaligned, prolly due to float precision.

I have a prefab that is a UICanvas in another prefab, which then was in the open scene.

**Steps to reproduce:**

I don't know :(

**Minimal reproduction project:**

none (if my project is needed for debugging, dm me on Discord: `saas._.`. It's on google drive anyways so I can send it over)

**Flax version:**

latest master (1.9.6605)

**Comment by mafiesto4** [comment]
Fixed in 12f3f00f9f6414c49e5d96a15af93cceafa19168.
