### ISSUE TITLE
[BUG] Editor stuck at *reloading scripts* (amongst other things) after compiling scripts

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#3079]
**Issue description:**

I get this warning/ error blob
```
[ 00:00:19.551 ]: Exception has been thrown during Main thread action. Object reference not set to an instance of an object.
Stack strace:
   at FlaxEngine.Interop.NativeInterop.RaiseException(ManagedHandle exceptionHandle) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 766
   at FlaxEngine.Actor.<Internal_GetLocalPosition>g____PInvoke|103_0(IntPtr ____obj_native, Vector3* ____resultAsRef_native)
   at FlaxEngine.Actor.get_LocalPosition() in D:\a\FlaxEngine\FlaxEngine\Cache\Intermediate\FlaxEditor\Windows\x64\Development\Level\Level.Bindings.Gen.cs:line 403
   at FlaxEngine.UIControl.OnControlLocationChanged(Control control) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\UIControl.cs:line 283
   at FlaxEngine.GUI.Control.UpdateBounds() in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\Control.Bounds.cs:line 482
   at FlaxEngine.GUI.ContainerControl.OnSizeChanged() in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1337
   at FlaxEngine.GUI.Control.UpdateBounds() in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\Control.Bounds.cs:line 487
   at FlaxEngine.GUI.Control.SetBounds(Rectangle& value) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\Control.Bounds.cs:line 353
   at FlaxEngine.GUI.Control.set_Size(Float2 value) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\Control.Bounds.cs:line 242
   at FlaxEngine.GUI.HorizontalPanel.PerformLayoutAfterChildren() in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\Panels\HorizontalPanel.cs:line 81
   at FlaxEngine.GUI.ContainerControl.PerformLayout(Boolean force) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 876
   at FlaxEngine.GUI.ContainerControl.PerformLayout(Boolean force) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 864
   at FlaxEngine.GUI.ContainerControl.PerformLayout(Boolean force) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 864
   at FlaxEngine.GUI.Panel.PerformLayout(Boolean force) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\Panels\Panel.cs:line 512
   at FlaxEngine.GUI.ContainerControl.PerformLayout(Boolean force) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 864
   at FlaxEngine.GUI.ContainerControl.PerformLayout(Boolean force) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 864
   at FlaxEngine.GUI.ContainerControl.PerformLayout(Boolean force) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 864
   at FlaxEngine.GUI.ContainerControl.PerformLayout(Boolean force) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 864
   at FlaxEngine.GUI.Control.set_Parent(ContainerControl value) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\Control.cs:line 122
   at FlaxEngine.UICanvas.Setup() in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\UICanvas.cs:line 515
   at FlaxEngine.UICanvas.EditorOverride(SceneRenderTask task, ContainerControl root) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\UICanvas.cs:line 836
   at FlaxEditor.Viewport.Previews.PrefabPreview.UpdateLinkage() in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Viewport\Previews\PrefabPreview.cs:line 105
   at FlaxEditor.Viewport.Previews.PrefabPreview.set_Instance(Actor value) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Viewport\Previews\PrefabPreview.cs:line 94
   at FlaxEditor.Viewport.Previews.PrefabPreview.set_Prefab(Prefab value) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Viewport\Previews\PrefabPreview.cs:line 57
   at FlaxEditor.Windows.Assets.PrefabWindow.OnPrefabOpened() in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.cs:line 357
   at FlaxEditor.Windows.Assets.PrefabWindow.OnScriptsReloadEnd() in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Windows\Assets\PrefabWindow.cs:line 329
   at FlaxEditor.ScriptsBuilder.Internal_OnEvent(EventType type) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Scripting\ScriptsBuilder.cs:line 125
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerStaticNoRet1`1.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 609
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 806
[ 00:00:19.551 ]: Exception has been thrown during Main thread action.
Object reference not set to an instance of an object.
```
after script are recompiling.
Also the editor is stuck at *reloading scripts* after that and the scene tree and properties panel disappear in my ui prefab. At least when it's editor is focused:
![image](https://github.com/user-attachments/assets/d051673a-77ae-4076-a681-89170b65c30d)

If that's not the case (open in a docked tab, but tab is not focused), and you focus back to the ui prefab editor tab after compiling scripts, this happens:
![image](https://github.com/user-attachments/assets/a369581f-0392-44df-93ab-822622ec0afe)

**Steps to reproduce:**

0. Download and unzip the zipped folder found in *Minimal reproduction project*
1. Open the folder and add the prefab in into your project and open it
2. Open the prefab
3. Either dock it in the main editor window or open it in a separate window
4. Recompile scripts and watch the chaos unfold

**Minimal reproduction project:**

[UI_Quest.zip](https://github.com/user-attachments/files/17908462/UI_Quest.zip)

**Flax version:**

1.9.6605

**Comment by mafiesto4** [comment]
Fixed in e7051824b77f14c032cb3b369ca04e9c12465ecf.
