### ISSUE TITLE
[Bug] List of type JsonAssetReference with EditorPlugin produces errors

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#3081]
**Issue description:**
This is a wild one. I have `EditorPlugin`s for json assets, to let them have unique icons. If there is a `List<T>` of type `JsonAssetReference<T>`, where the json asset are affected by the `EditorPlugin`, an error like this is thrown on script compilation:

```
[ 00:10:36.028 ]: [Info] Unloading plugin byteslider.InteractionSystem.MyGlobalEventEditorPlugin
[ 00:10:36.031 ]: [Warning] Exception has been thrown during EditorPlugin. Object reference not set to an instance of an object.
Stack strace:
   at FlaxEditor.CustomEditors.Editors.AssetRefEditor.OnSelectedItemChanged() in D:\a\FlaxEngine\FlaxEngine\Source\Editor\CustomEditors\Editors\AssetRefEditor.cs:line 81
   at FlaxEditor.GUI.AssetPicker.OnSelectedItemChanged() in D:\a\FlaxEngine\FlaxEngine\Source\Editor\GUI\AssetPicker.cs:line 89
   at FlaxEditor.Content.AssetPickerValidator.OnSelectedItemChanged() in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Content\AssetPickerValidator.cs:line 237
   at FlaxEditor.Content.AssetPickerValidator.set_SelectedItem(ContentItem value) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Content\AssetPickerValidator.cs:line 47
   at FlaxEditor.Content.AssetPickerValidator.OnItemDispose(ContentItem item) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Content\AssetPickerValidator.cs:line 260
   at FlaxEditor.Content.ContentItem.OnDestroy() in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Content\Items\ContentItem.cs:line 863
   at FlaxEditor.Modules.ContentDatabaseModule.Dispose(ContentItem item) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Modules\ContentDatabaseModule.cs:line 868
   at FlaxEditor.Modules.ContentDatabaseModule.LoadFolder(ContentTreeNode node, Boolean checkSubDirs) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Modules\ContentDatabaseModule.cs:line 885
   at FlaxEditor.Modules.ContentDatabaseModule.RebuildInternal() in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Modules\ContentDatabaseModule.cs:line 830
   at FlaxEditor.Modules.ContentDatabaseModule.Rebuild(Boolean immediate) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Modules\ContentDatabaseModule.cs:line 806
   at FlaxEditor.Modules.ContentDatabaseModule.RemoveProxy(ContentProxy proxy, Boolean rebuild) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Modules\ContentDatabaseModule.cs:line 795
   at byteslider.InteractionSystem.MyGlobalEventEditorPlugin.DeinitializeEditor() in C:\Users\Thomas\Documents\Flax Projects\FlaxSamples\BasicTemplate\Source\InteractionSystem\MyGlobalEventEditorPlugin.cs:line 33
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet0`1.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 291
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 806 
[ 00:10:36.031 ]: [Error] Exception has been thrown during EditorPlugin.
Object reference not set to an instance of an object. 
```

This may or may not lead to a number of ui bugs. `Content` assets showing up in `Source`, the `Content View` being empty, dragging and dropping scripts on an actor not working, or the actor or script holding that list gets reset (big issue in current game project). 

**Steps to reproduce:**

1. Create a class for a json asset, like `MyClass`
2. Create a `EditorPlugin` and a `JsonAssetItem` proxy for that class
3. Create a new script or an actor with a list `List<JsonAssetReferecence<MyClass>>`
4. Populate the list with a json asset
5. Have the scripts recompile

Attached a minimal project, just to be sure. Open the project and `Recompile Scripts`
[BasicTemplate.zip](https://github.com/user-attachments/files/17960472/BasicTemplate.zip)

**Minimal reproduction project:**
Basic

**Flax version:**
1.9.6605 (master 29.11.24)

**Comment by mafiesto4** [comment]
Fixed in 139a43161404c4bf6b2f5e636ea8265ba8ed8170,

**Comment by Myterian** [comment]
Hey, quick follow up. The icons are fixed, so that's not an issue anymore. But there is a new issue, because `Lists` of type `JsonAssetReference` throw this warning when trying to add or remove an element in editor and the list does not change

```
[ 02:46:06.149 ]: [Warning] Exception: Object of type 'FlaxEngine.JsonAssetReference`1[byteslider.ItemsAndInventory.ItemClass]' cannot be converted to type 'System.Collections.Generic.List`1[FlaxEngine.JsonAssetReference`1[byteslider.ItemsAndInventory.ItemClass]]'.
[ 02:46:06.150 ]: [Warning]    at System.RuntimeType.CheckValue(Object& value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at FlaxEditor.Scripting.ScriptMemberInfo.SetValue(Object obj, Object value) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\Scripting\ScriptType.cs:line 688
   at FlaxEditor.CustomEditors.ValueContainer.Set(ValueContainer instanceValues, Object value) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\CustomEditors\Values\ValueContainer.cs:line 393
   at FlaxEditor.CustomEditors.CustomEditor.SynchronizeValue(Object value) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 334
   at FlaxEditor.CustomEditors.CustomEditor.RefreshInternal() in D:\a\FlaxEngine\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 364
   at FlaxEditor.CustomEditors.CustomEditor.RefreshRootChild() in D:\a\FlaxEngine\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 325
   at FlaxEditor.CustomEditors.CustomEditor.RefreshRoot() in D:\a\FlaxEngine\FlaxEngine\Source\Editor\CustomEditors\CustomEditor.cs:line 278
   at FlaxEditor.CustomEditors.SyncPointEditor.RefreshInternal() in D:\a\FlaxEngine\FlaxEngine\Source\Editor\CustomEditors\SyncPointEditor.cs:line 80
   at FlaxEditor.CustomEditors.CustomEditorPresenter.PresenterPanel.Update(Single deltaTime) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\CustomEditors\CustomEditorPresenter.cs:line 91
```

**Comment by Tryibion** [comment]
Can you see if <https://github.com/FlaxEngine/FlaxEngine/pull/3109> has fixed the 2nd issue?

**Comment by Myterian** [comment]
Yep, looks good
