### ISSUE TITLE
Unable to Cook the Game due to error in \FlaxEngine\Source\Engine\UI\UICanvas.cs

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#381]
**Issue description:**
I've just tried to cook my game and received the following errors. It appears that there is a problem with the UICanvas probably introduced as a result of all the bug fixes.

```
[ 00:22:25.256 ]: [Info] Compiling C:\Users\Richard\Documents\FlaxEngine\Source\Platforms\Windows\Binaries\Game\x64\Release\FlaxEngine.CSharp.dll
[ 00:22:27.265 ]: [Info] C:\Users\Richard\Documents\FlaxEngine\Source\Engine\UI\UICanvas.cs(120,69,120,80): error CS0103: The name 'Editor_Is3D' does not exist in the current context
[ 00:22:27.329 ]: [Info] Task C:\Users\Richard\Documents\FlaxEngine\Source\Platforms\Editor\Windows\Mono\bin\mono.exe "C:\Users\Richard\Documents\FlaxEngine\Source\Platforms\Editor\Windows\Mono\lib\mono\4.5\csc.exe" /noconfig @"C:\Users\Richard\Documents\FlaxEngine\Cache/Intermediate\FlaxGame\Windows\x64\Release\FlaxEngine.CSharp.response" failed with exit code 1

1 task failed
[ 00:22:27.934 ]: [Info] Exception: Failed to build target FlaxGame. See log.
Stack trace:
[ 00:22:27.950 ]: [Info]    at Flax.Build.Builder.BuildTargetReferenceNativeCpp(Dictionary`2 buildContext, BuildData buildData, Reference reference) in C:\Users\Richard\Documents\FlaxEngine\Source\Tools\Flax.Build\Build\NativeCpp\Builder.NativeCpp.cs:line 523
   at Flax.Build.Builder.BuildTargetNativeCppBindingsOnly(RulesAssembly rules, TaskGraph graph, Target target, Dictionary`2 buildContext, Platform platform, TargetArchitecture architecture, TargetConfiguration configuration) in C:\Users\Richard\Documents\FlaxEngine\Source\Tools\Flax.Build\Build\NativeCpp\Builder.NativeCpp.cs:line 1000
   at Flax.Build.Builder.BuildTargets() in C:\Users\Richard\Documents\FlaxEngine\Source\Tools\Flax.Build\Build\Builder.cs:line 178
   at Flax.Build.Program.Main() in C:\Users\Richard\Documents\FlaxEngine\Source\Tools\Flax.Build\Program.cs:line 135
Total time: 00:00:04.7432940
[ 00:22:27.966 ]: [Error] Failed to compile game scripts.
[ 00:22:27.966 ]: [Error] Game building failed!
```

![image](https://user-images.githubusercontent.com/35228400/112086695-cb057600-8be0-11eb-948f-d5984b6713a0.png)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Fixed in 22812ad21e1745f7eb1e7a38a4d72d52a59ea80e.
