### ISSUE TITLE
Missing game modules. Cannot load scene without game script modules

### ISSUE THREAD

**Issue by sonczyponcze** [FlaxEngine/FlaxEngine#614]
Po instalacji Android Studio + JDK występuje powyższy błąd. 
Flax Engine 1.2

[Log_2021_08_24_18_53_56.txt](https://github.com/FlaxEngine/FlaxEngine/files/7040872/Log_2021_08_24_18_53_56.txt)

**Comment by mafiesto4** [comment]
Relevant log part:
```
Exception: The type initializer for 'Flax.Build.Platforms.AndroidNdk' threw an exception.
Stack trace:
   at Flax.Build.Platforms.AndroidPlatform..ctor()
Inner exception:
Exception: Could not find file 'C:\Users\soncz\AppData\Local\Android\Sdk\source.properties'.
Stack trace:
[ 00:00:05.128 ]: [Info]    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at Flax.Build.Platforms.AndroidNdk..ctor()
   at Flax.Build.Platforms.AndroidNdk..cctor()
   ```

File used to detect NDK version is missing: `C:\Users\soncz\AppData\Local\Android\Sdk\source.properties`.

**Comment by mafiesto4** [comment]
Fixed in df10581bb25daf54b3a15831f04ddfdb895cfcd3
